### ISSUE TITLE
<Link> gives unstyled <a> without href attribute

### ISSUE THREAD

**Issue by aspiers** [fisshy/react-scroll#363]
When hovering over links generated using react-scroll's `<Link>`, I noticed that my mouse pointer didn't change to the expected hand+forefinger icon.  This styling is determined by the user agent stylesheet built into the browser, e.g. for Chrome:

```css
a:-webkit-any-link {
    cursor: pointer;
}
```

and for Firefox:

```css
*|*:any-link {
  cursor: pointer;
}
```

It took me ages to realise that this styling only applies when the `<a>` element has an `href` attribute present, and `<Link>` doesn't provide an `href` attribute to its `<a>` element by default.  Fortunately this is easy to fix just by adding `href="#"` or similar to `<Link>`.  However since I wasted literally hours figuring this out, it would be good if it was documented so that others don't have to go through the same struggle.
