### ISSUE TITLE
Link not working with tailwind-scrollbar

### ISSUE THREAD

**Issue by DaliborTrampota** [fisshy/react-scroll#508]
when applying this class (scrollbar-thin or scrollbar) to my scroll bars, Link element stops working. 
these are the css properties: 
```css
.scrollbar-thin {
    --scrollbar-track: initial !important;
    --scrollbar-thumb: initial !important;
    scrollbar-color: var(--scrollbar-thumb) var(--scrollbar-track) !important;
    overflow: overlay !important;
}
.scrollbar-thin.overflow-x-hidden {
    overflow-x: hidden !important;
}
.scrollbar-thin.overflow-y-hidden {
    overflow-y: hidden !important;
}
.scrollbar-thin::-webkit-scrollbar-track {
    background-color: var(--scrollbar-track) !important;
}
.scrollbar-thin::-webkit-scrollbar-thumb {
    background-color: var(--scrollbar-thumb) !important;
}
.scrollbar-thin {
    scrollbar-width: thin !important;
}
.scrollbar-thin::-webkit-scrollbar {
    width: 8px !important;
    height: 8px !important;
}
```

I'd like to have my scrollbar custom but I'd also like to have the smooth scroll. Now it doesnt redirect at all, the a element has no href property nor it jumps to the id.
